# Generated by Django 3.1 on 2020-08-29 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_auto_20200828_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='date_adde',
            new_name='date_added',
        ),
    ]
